project:
  type: website

website:
  title: "Skyler Elmstrom's Blog"
  site-url: https://blog.skylere.com
  navbar:
    right:
      - icon: github
        href: https://github.com/SkylerElmstrom
      - icon: rss
        href: index.xml
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual

execute:
  freeze: auto

