project:
  type: website

website:
  title: "Skyler's Blog"
  navbar:
    right:
      # - about.qmd
      - icon: github
        href: https://github.com/SkylerElmstrom
      - icon: rss
        href: index.xml
      # - icon: twitter
      #   href: https://twitter.com
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual

execute:
  freeze: auto

